2015/11/17 10:48:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/17 10:48:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 07:56:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:02:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:10:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:10:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:12:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:12:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:13:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:39:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:57:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 08:58:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 09:07:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "themes/activity/images/arr.png".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('themes/activity...')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/themes/activity/images/arr.png
HTTP_REFERER=http://localhost/activity/themes/activity/style.css
---
2015/11/18 09:07:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "blog".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('blog')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/blog
---
2015/11/18 09:08:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "blog".' in C:\xampp\htdocs\activity\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('blog')
#1 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#3 {main}
REQUEST_URI=/activity/blog
HTTP_REFERER=http://localhost/activity/blog
---
2015/11/18 09:32:27 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'where clause'. The SQL statement executed was: select * from at_activity where id in (Array).
in C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php (317)
in C:\xampp\htdocs\activity\index.php (14)
2015/11/18 09:32:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'where clause'. The SQL statement executed was: select * from at_activity where id in (Array)' in C:\xampp\htdocs\activity\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\activity\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php(317): CDbCommand->queryAll()
#2 C:\xampp\htdocs\activity\framework\web\actions\CInlineAction.php(49): AtUsersController->actionPartnerdtls()
#3 C:\xampp\htdocs\activity\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\activity\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\activity\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(282): CController->run('partnerdtls')
#7 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('atUsers/partner...')
#8 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#10 {main}
REQUEST_URI=/activity/atUsers/partnerdtls
HTTP_REFERER=http://localhost/activity/blog
---
2015/11/18 09:32:29 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'where clause'. The SQL statement executed was: select * from at_activity where id in (Array).
in C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php (317)
in C:\xampp\htdocs\activity\index.php (14)
2015/11/18 09:32:29 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Array' in 'where clause'. The SQL statement executed was: select * from at_activity where id in (Array)' in C:\xampp\htdocs\activity\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\activity\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php(317): CDbCommand->queryAll()
#2 C:\xampp\htdocs\activity\framework\web\actions\CInlineAction.php(49): AtUsersController->actionPartnerdtls()
#3 C:\xampp\htdocs\activity\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\activity\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\activity\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(282): CController->run('partnerdtls')
#7 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('atUsers/partner...')
#8 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#10 {main}
REQUEST_URI=/activity/atUsers/partnerdtls
HTTP_REFERER=http://localhost/activity/atUsers/partnerdtls
---
2015/11/18 09:44:47 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e980099' at line 8. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`,
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' ).
in C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php (520)
in C:\xampp\htdocs\activity\index.php (14)
2015/11/18 09:44:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e980099' at line 8. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`,
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' )' in C:\xampp\htdocs\activity\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php(520): CDbCommand->execute()
#1 C:\xampp\htdocs\activity\framework\web\actions\CInlineAction.php(49): AtUsersController->actionAddPartnerActivity()
#2 C:\xampp\htdocs\activity\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\activity\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\activity\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(282): CController->run('addpartneractiv...')
#6 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('atUsers/addpart...')
#7 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/activity/atUsers/addpartneractivity
HTTP_REFERER=http://localhost/activity/atUsers/partnerdtls
---
2015/11/18 09:44:49 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e980099' at line 8. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`,
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' ).
in C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php (520)
in C:\xampp\htdocs\activity\index.php (14)
2015/11/18 09:44:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e980099' at line 8. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`,
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' )' in C:\xampp\htdocs\activity\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php(520): CDbCommand->execute()
#1 C:\xampp\htdocs\activity\framework\web\actions\CInlineAction.php(49): AtUsersController->actionAddPartnerActivity()
#2 C:\xampp\htdocs\activity\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\activity\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\activity\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(282): CController->run('addpartneractiv...')
#6 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('atUsers/addpart...')
#7 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/activity/atUsers/addpartneractivity
HTTP_REFERER=http://localhost/activity/atUsers/addpartneractivity
---
2015/11/18 09:45:58 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' ).
in C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php (520)
in C:\xampp\htdocs\activity\index.php (14)
2015/11/18 09:45:58 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' )' in C:\xampp\htdocs\activity\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php(520): CDbCommand->execute()
#1 C:\xampp\htdocs\activity\framework\web\actions\CInlineAction.php(49): AtUsersController->actionAddPartnerActivity()
#2 C:\xampp\htdocs\activity\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\activity\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\activity\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(282): CController->run('addpartneractiv...')
#6 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('atUsers/addpart...')
#7 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/activity/atUsers/addpartneractivity
HTTP_REFERER=http://localhost/activity/atUsers/partnerdtls
---
2015/11/18 09:45:59 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' ).
in C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php (520)
in C:\xampp\htdocs\activity\index.php (14)
2015/11/18 09:45:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1. The SQL statement executed was:  INSERT INTO `at_partner_activity` (
            `user_id` ,
            `activity_type_id` ,
            `age_range` ,
            `activity_date`,
            `activity_time`
          
            )
            VALUES (
            '',  '',  '','','','d41d8cd98f00b204e9800998ecf8427e','','JA==' )' in C:\xampp\htdocs\activity\framework\db\CDbCommand.php:358
Stack trace:
#0 C:\xampp\htdocs\activity\protected\controllers\AtUsersController.php(520): CDbCommand->execute()
#1 C:\xampp\htdocs\activity\framework\web\actions\CInlineAction.php(49): AtUsersController->actionAddPartnerActivity()
#2 C:\xampp\htdocs\activity\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 C:\xampp\htdocs\activity\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 C:\xampp\htdocs\activity\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(282): CController->run('addpartneractiv...')
#6 C:\xampp\htdocs\activity\framework\web\CWebApplication.php(141): CWebApplication->runController('atUsers/addpart...')
#7 C:\xampp\htdocs\activity\framework\base\CApplication.php(184): CWebApplication->processRequest()
#8 C:\xampp\htdocs\activity\index.php(14): CApplication->run()
#9 {main}
REQUEST_URI=/activity/atUsers/addpartneractivity
HTTP_REFERER=http://localhost/activity/atUsers/addpartneractivity
---
